=== Sbord1/lweb22-23-XMLconDOM/movies.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- L'oggetto "movies" e' l'elemento radice del documento ed e' specificato come una sequenza di elementi "film" (0 o piu') -->
<!ELEMENT movies (film*)>

<!ELEMENT film (id, director, title, year?, quantity, price)>

<!ATTLIST film
            category (avventura | azione | fantascienza | poliziesco | storico | thriller) #REQUIRED>

<!ELEMENT id (#PCDATA)>

<!ELEMENT director (name, surname)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>

<!ELEMENT title (#PCDATA)>

<!ELEMENT year (#PCDATA)>

<!ELEMENT quantity (#PCDATA)>

<!ELEMENT price (#PCDATA)>

=== Sbord1/lweb22-23-XMLconDOM/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movies SYSTEM "movies.dtd">
<movies><film category="azione"><id>1</id><director><name>Christopher</name><surname>McQuarrie</surname></director><title>Mission Impossible</title><year>2018</year><quantity>9</quantity><price>120</price><imgPath>locandine/azione/MissionImpossible.jpeg</imgPath></film><film category="azione"><id>2</id><director><name>Quentin</name><surname>Tarantino</surname></director><title>KillBill</title><year>2003</year><quantity>6</quantity><price>120</price><imgPath>locandine/azione/KillBill.jpeg</imgPath></film><film category="azione"><id>3</id><director><name>Chad</name><surname>Stahelski</surname></director><title>John Wick</title><year>2014</year><quantity>1</quantity><price>120</price><imgPath>locandine/azione/JohnWick.jpeg</imgPath></film><film category="azione"><id>4</id><director><name>Park</name><surname>Chan-wook</surname></director><title>Old Boy</title><year>2005</year><quantity>2</quantity><price>120</price><imgPath>locandine/azione/OldBoy.jpeg</imgPath></film><film category="azione"><id>5</id><director><name>Olivier</name><surname>Megaton</surname></director><title>Taken</title><year>2014</year><quantity>10</quantity><price>120</price><imgPath>locandine/azione/Taken.jpeg</imgPath></film><film category="azione"><id>6</id><director><name>Brett</name><surname>Bratner</surname></director><title>Tower Heist</title><year>2011</year><quantity>2</quantity><price>120</price><imgPath>locandine/azione/TowerHeist.jpeg</imgPath></film><film category="azione"><id>7</id><director><name>Quentin</name><surname>Tarantino</surname></director><title>Bastardi Senza Gloria</title><year>2009</year><quantity>1</quantity><price>150</price><imgPath>locandine/azione/BastardiSenzaGloria.jpeg</imgPath></film><film category="azione"><id>8</id><director><name>Joe</name><surname>Carnahan</surname></director><title>A-Team</title><year>2010</year><quantity>8</quantity><price>120</price><imgPath>locandine/azione/ATeam.jpeg</imgPath></film><film category="avventura"><id>1</id><director><name>Alejandro</name><surname>Inarritu</surname></director><title>Revenant</title><year>2016</year><quantity>3</quantity><price>120</price><imgPath>locandine/avventura/revenant.jpeg</imgPath></film><film category="avventura"><id>2</id><director><name>Joe</name><surname>Johnston</surname></director><title>Jumanji</title><year>1995</year><quantity>5</quantity><price>130</price><imgPath>locandine/avventura/jumanji.jpeg</imgPath></film><film category="avventura"><id>3</id><director><name>James</name><surname>Cameron</surname></director><title>Avatar</title><year>2009</year><quantity>2</quantity><price>90</price><imgPath>locandine/avventura/avatar.jpeg</imgPath></film><film category="avventura"><id>4</id><director><name>Colin</name><surname>Trevorrow</surname></director><title>Jurassic World</title><year>2015</year><quantity>6</quantity><price>100</price><imgPath>locandine/avventura/jurassic world.jpeg</imgPath></film><film category="avventura"><id>5</id><director><name>Baltasar</name><surname>Kormakur</surname></director><title>Everest</title><year>2015</year><quantity>1</quantity><price>80</price><imgPath>locandine/avventura/everest.jpeg</imgPath></film><film category="avventura"><id>6</id><director><name>Ruben</name><surname>Fleischer</surname></director><title>Uncharted</title><year>2022</year><quantity>5</quantity><price>125</price><imgPath>locandine/avventura/uncharted.jpeg</imgPath></film><film category="fantascienza"><id>1</id><director><name>Denis</name><surname>Villeneuve</surname></director><title>Dune</title><year>2021</year><quantity>9</quantity><price>120</price><imgPath>locandine/fantascienza/Dune.jpeg</imgPath></film><film category="fantascienza"><id>2</id><director><name>George</name><surname>Lucas</surname></director><title>Star Wars</title><year>1999</year><quantity>5</quantity><price>120</price><imgPath>locandine/fantascienza/starwars.jpeg</imgPath></film><film category="fantascienza"><id>3</id><director><name>David</name><surname>Yates</surname></director><title>Harry Potter</title><year>2011</year><quantity>3</quantity><price>120</price><imgPath>locandine/fantascienza/HarryPotter.jpeg</imgPath></film><film category="fantascienza"><id>4</id><director><name>Tim</name><surname>Burton</surname></director><title>La fabbrica di cioccolato</title><year>2005</year><quantity>8</quantity><price>120</price><imgPath>locandine/fantascienza/LaFabbricadiCioccolato.jpeg</imgPath></film><film category="fantascienza"><id>5</id><director><name>Chris</name><surname>Buck</surname></director><title>Frozen</title><year>2013</year><quantity>4</quantity><price>120</price><imgPath>locandine/fantascienza/frozen.jpeg</imgPath></film><film category="fantascienza"><id>6</id><director><name>Peter</name><surname>Jackson</surname></director><title>Lo Hobbit</title><year>2012</year><quantity>4</quantity><price>120</price><imgPath>locandine/fantascienza/Hobbit.jpeg</imgPath></film><film category="fantascienza"><id>7</id><director><name>Anthony</name><surname>Russo</surname></director><title>Avengers</title><year>2019</year><quantity>7</quantity><price>120</price><imgPath>locandine/fantascienza/Avengers.jpeg</imgPath></film><film category="fantascienza"><id>8</id><director><name>Dennis</name><surname>Villeneuve</surname></director><title>Blade runner</title><year>2017</year><quantity>12</quantity><price>120</price><imgPath>locandine/fantascienza/bladerunner.jpeg</imgPath></film><film category="fantascienza"><id>9</id><director><name>Alex</name><surname>Proyas</surname></director><title>Segnali dal futuro</title><year>2009</year><quantity>2</quantity><price>120</price><imgPath>locandine/fantascienza/segnalifuturo.jpeg</imgPath></film><film category="poliziesco"><id>1</id><director><name>Martin</name><surname>Scorsese</surname></director><title>The Departed</title><year>2006</year><quantity>4</quantity><price>120</price><imgPath>locandine/poliziesco/thedeparted.jpg</imgPath></film><film category="poliziesco"><id>2</id><director><name>Brian</name><surname>Helgeland</surname></director><title>Legend</title><year>2015</year><quantity>7</quantity><price>120</price><imgPath>locandine/poliziesco/legend.jpg</imgPath></film><film category="poliziesco"><id>3</id><director><name>Guy</name><surname>Ritchie</surname></director><title>Sherlock Holmes</title><year>2009</year><quantity>2</quantity><price>120</price><imgPath>locandine/poliziesco/sherlockholmes.jpg</imgPath></film><film category="poliziesco"><id>4</id><director><name>Doug</name><surname>Liman</surname></director><title>Barry Seal</title><year>2017</year><quantity>3</quantity><price>120</price><imgPath>locandine/poliziesco/barryseal.jpg</imgPath></film><film category="poliziesco"><id>5</id><director><name>Antonio</name><surname>Manetti</surname></director><title>Diabolik</title><year>2022</year><quantity>1</quantity><price>120</price><imgPath>locandine/poliziesco/diabolik.jpg</imgPath></film><film category="poliziesco"><id>6</id><director><name>Ben</name><surname>Affleck</surname></director><title>Gone Baby Gone</title><year>2007</year><quantity>5</quantity><price>120</price><imgPath>locandine/poliziesco/gonebabygone.jpg</imgPath></film><film category="poliziesco"><id>7</id><director><name>Marco</name><surname>Bellocchio</surname></director><title>Il traditore</title><year>2019</year><quantity>14</quantity><price>120</price><imgPath>locandine/poliziesco/iltraditore.jpg</imgPath></film><film category="poliziesco"><id>8</id><director><name>Spike</name><surname>Lee</surname></director><title>Inside Man</title><year>2006</year><quantity>2</quantity><price>120</price><imgPath>locandine/poliziesco/insideman.jpg</imgPath></film><film category="poliziesco"><id>9</id><director><name>Antoine</name><surname>Fuqua</surname></director><title>Training day</title><year>2001</year><quantity>5</quantity><price>120</price><imgPath>locandine/poliziesco/trainingday.jpg</imgPath></film><film category="storico"><id>1</id><director><name>Christopher</name><surname>Nolan</surname></director><title>Dunkirk</title><year>2017</year><quantity>11</quantity><price>120</price><imgPath>locandine/storico/dunkirk.jpg</imgPath></film><film category="storico"><id>2</id><director><name>Alfonso</name><surname>Gomez-Rejon</surname></director><title>Edison</title><year>2017</year><quantity>9</quantity><price>120</price><imgPath>locandine/storico/edison.jpg</imgPath></film><film category="storico"><id>3</id><director><name>Ridley</name><surname>Scott</surname></director><title>Il Gladiatore</title><year>2000</year><quantity>12</quantity><price>120</price><imgPath>locandine/storico/ilgladiatore.jpg</imgPath></film><film category="storico"><id>4</id><director><name>Matteo</name><surname>Rovere</surname></director><title>Il primo Re</title><year>2019</year><quantity>7</quantity><price>120</price><imgPath>locandine/storico/ilprimore.jpg</imgPath></film><film category="storico"><id>5</id><director><name>Aaron</name><surname>Sorkin</surname></director><title>Il Processo ai Chicago 7</title><year>2020</year><quantity>4</quantity><price>120</price><imgPath>locandine/storico/ilprocessoai7.jpg</imgPath></film><film category="storico"><id>6</id><director><name>Maximiliano</name><surname>Bruno</surname></director><title>Red Land</title><year>2018</year><quantity>15</quantity><price>120</price><imgPath>locandine/storico/redland.jpg</imgPath></film><film category="storico"><id>7</id><director><name>Ava</name><surname>DuVernay</surname></director><title>Selma</title><year>2014</year><quantity>1</quantity><price>120</price><imgPath>locandine/storico/selma.jpg</imgPath></film><film category="storico"><id>8</id><director><name>Paul</name><surname>Williams</surname></director><title>The Eichmann Show</title><year>2015</year><quantity>3</quantity><price>120</price><imgPath>locandine/storico/theeichmannshow.jpg</imgPath></film><film category="storico"><id>9</id><director><name>Mortem</name><surname>Tyldum</surname
